require("config.globals")
require("config.options")
require("config.keymaps")
require("config.autocmds")
require("config.usercmds")
require("config.diagnostics")

require("plugins.utils")
require("plugins.colorscheme")
require("plugins.fff")
require("plugins.lsp")
require("plugins.completions")
require("plugins.formatting")
require("plugins.nvim-treesitter")
