# Shared terminal environment. Tool fragments are generated by Ansible.
# This file is POSIX sh: source it from Bash or the interactive-shell launcher.
shell_prepend_path() {
    case ":${PATH}:" in
        *:"$1":*) ;;
        *) PATH="$1${PATH:+:$PATH}" ;;
    esac
    export PATH
}

shell_prepend_path "$HOME/.local/bin"
export EDITOR=nvim

for shell_env_file in "${XDG_CONFIG_HOME:-$HOME/.config}"/shell/env.d/*.sh; do
    [ -r "$shell_env_file" ] || continue
    . "$shell_env_file"
done
unset shell_env_file
unset -f shell_prepend_path
