XDG_CONFIG_HOME=$HOME/.config
XDG_CACHE_HOME=$HOME/.cache
XDG_DATA_HOME=$HOME/.local/share
XDG_STATE_HOME=$HOME/.local/state

EDITOR=nvim

PNPM_HOME=$XDG_DATA_HOME/pnpm

JAVA_HOME=$HOME/opt/java/jdk-24.0.1
GOROOT=/usr/local/go
GOPATH=$XDG_DATA_HOME/go
CARGO_HOME=$XDG_DATA_HOME/cargo
RUSTUP_HOME=$XDG_DATA_HOME/rustup

# Custom FFmpeg with VMAF
LD_LIBRARY_PATH=$HOME/ffmpeg-build/lib:$LD_LIBRARY_PATH

PATH=$HOME/.local/bin:$HOME/.opencode/bin:$HOME/.bun/bin:$HOME/ffmpeg-build/bin:$PNPM_HOME/bin:$CARGO_HOME/bin:$GOPATH/bin:$GOROOT/bin:$JAVA_HOME/bin:$PATH
